config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  get 'add_address' => 'contacts#add_address'
  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/contact.rb
class Contact < ApplicationRecord
	has_many :addresses, :dependent => :delete_all
	has_many :phonenumbers, :dependent => :delete_all
	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
	validates_presence_of :email
	validates :email, :uniqueness => {:case_sensitive => false}
	validates_numericality_of :age
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  ##used before_action because some lines are common to these method
  before_action :load_contact_details, only: [:show, :edit, :update]

  def index
    @contacts = Contact.all
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new contact_params
    #creates associated address and phone number objects
    @address = @contact.addresses.build(address_params)
    @phonenumber = @contact.phonenumbers.build(phonenumber_params)
    begin
      #Used transaction block to avoid data loss. If anything fails inside transaction block all the items will rollback.
      Contact.transaction do
        @contact.save!
        @address.save!
        @phonenumber.save!
      end
    rescue
      flash[:notice] = "Contact failed to create!"
      render :action => 'new'
    else
      Rails.logger.info "Contact has been saved successfully!"
      flash[:notice] = "Contact saved successfully!"
      redirect_to contacts_path
    end
  end

  def show
    #data will be loaded from before_action
  end

  def edit
    #data will be loaded from before_action
  end

  def update
    begin
      Contact.transaction do
        @contact.update_attributes! contact_params
        @address.update_attributes! address_params
        @phonenumber.update_attributes! phonenumber_params
      end
    rescue
      flash[:notice] = "Contact failed to update!"
      render :action => :edit
    else
      flash[:notice] = "Contact updated successfully!"
      redirect_to contacts_path
    end
  end

  def destroy
    @contact = Contact.find params[:id]
    @contact.destroy
    Rails.logger.info "Contact #{@contact.first_name} deleted successfully!"
    flash[:notice] = "Contact deleted successfully!"
    redirect_to contacts_path
  end

  def load_contact_details
    @contact = Contact.find params[:id]
    @address = @contact.addresses.first
    @phonenumber = @contact.phonenumbers.first
  end

  private

  #Used strong parameters to whitelist params. It protects from mass-assignment

  def contact_params
    params.require(:contact).permit(:first_name, :last_name, :email, :age)
  end

  def address_params
    params.require(:address).permit(:door_no, :street, :city, :state, :country)
  end

  def phonenumber_params
    params.require(:phonenumber).permit(:phone_number)
  end

end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_address.html.erb
<div class="address">
<h5>Address Details:</h5>
<%= fields_for :address do |f| %>
  <%= f.label 'Door No' %>
  <%=f.text_field :door_no, :required => true %></br>
  <%= f.label 'Street' %>
  <%=f.text_field :street %></br>
  <%= f.label 'City' %>
  <%=f.text_field :city %></br>
  <%= f.label 'State' %>
  <%=f.text_field :state %></br>
  <%= f.label 'Country' %>
  <%=f.text_field :country, :required => true%></br>
  <%end%>
  </div>

app/views/contacts/_form.html.erb
<div class="personal">
<h5>Personal Information:</h5>
<%= form_for @contact do |form| %>
  <% if @contact.errors.any? %>
    <% @contact.errors.full_messages.each do |message| %>
      <li class="errors"><%= message %></li>
    <% end %>
  <% end %>
  <%= form.label 'First Name' %>
  <%= form.text_field :first_name, :required => true%></br>
  <%= form.label 'Last Name' %>
  <%= form.text_field :last_name %></br>
  <%= form.label 'Email' %>
  <%= form.text_field :email, :required => true%></br>
  <%= form.label 'Age' %>
  <%= form.text_field :age %></br>
</div>
  <%= render :partial => 'address' %>
  <%= render :partial => 'phonenumber' %>
</br>
  <%= form.submit %>
<% end -%>

<style type="text/css">
	label {
    width:180px;
    clear:left;
    text-align:right;
    padding-right:10px;
    padding-bottom: 10px;
}

input, label {
    float:left;
}

.personal, .address, .phonenumber {
    width: 500px;
    border: 1px solid black;
    padding: 5px;
    margin: 5px;
}

.personal{
	height: 250px;
}
.address{
	height: 250px;
}
.phonenumber{
	height: 100px;
}
.errors{
	color: red;
}
</style>

app/views/contacts/_phonenumber.html.erb
<div class="phonenumber">
<h5>Phone Number:</h5>
<%= fields_for :phonenumber do |f| %>
  <% if @phonenumber && @phonenumber.errors.any? %>
    <% @phonenumber.errors.full_messages.each do |message| %>
      <li class="errors"><%= message %></li>
    <% end %>
  <% end %>
  <%= f.label 'Phone Number' %>
  <%=f.text_field :phone_number, :required => true%></br>
 <%end%>
 </br>
 </div>

app/views/contacts/create.html.erb
<h1>Contacts#create</h1>
<p>Find me in app/views/contacts/create.html.erb</p>

app/views/contacts/destroy.html.erb
<h1>Contacts#destroy</h1>
<p>Find me in app/views/contacts/destroy.html.erb</p>

app/views/contacts/edit.html.erb
<%= render :partial => 'form' %>

app/views/contacts/index.html.erb
<h1>List of Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3">Options</th>
    </tr>
  </thead>

  <% @contacts.each do |contact| %>
    <tr>
      <td><%= contact.first_name %></td>
      	<td><%= link_to 'show', contact %> </td>
        <td><%= link_to 'Edit', edit_contact_path(contact.id) %></td>
        <td><%= link_to 'Delete', contact, :method => 'delete' %></td>
    </tr>
  <% end -%>
</table>

<p><%= link_to 'New Contact', new_contact_path %></p>

<style>
table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
}

td, th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
}

tr:nth-child(even) {
    background-color: #dddddd;
}
</style>

app/views/contacts/new.html.erb
<%= render :partial => 'form' %>

app/views/contacts/show.html.erb
<h5>Personal Information:</h5>
<h3>First Name : <%= @contact.first_name %></h3>
<h3>Last Name : <%= @contact.last_name %></h3>
<h3>Email : <%= @contact.email %></h3>
<h3>Age : <%= @contact.age %></h3></br>
<h5>Address Details:</h5>
<h3>Door No : <%= @address.door_no %></h3>
<h3>Street : <%= @address.street %></h3>
<h3>City : <%= @address.city %></h3>
<h3>State : <%= @address.state %></h3>
<h3>Country : <%= @address.country %></h3></br>
<h5>Phone Number:</h5>
<h3>Phone Number : <%= @phonenumber.phone_number %></h3></br>

<a href="/contacts/<%=@contact.id %>/edit">Edit</a>
<a href="/contacts">Back</a>

app/views/contacts/update.html.erb
<h1>Contacts#update</h1>
<p>Find me in app/views/contacts/update.html.erb</p>